# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dotui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dotgui(object):
    def setupUi(self, dotgui):
        dotgui.setObjectName("dotgui")
        dotgui.resize(1229, 833)
        self.centralwidget = QtWidgets.QWidget(dotgui)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 1251, 861))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setStyleSheet("background:tranparent")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/7LP8.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(990, 770, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1080, 770, 91, 28))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 501, 101))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.BusyCursor))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Downloads/Jarvis_Loading_Screen.gif"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(620, 10, 271, 61))
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(850, 10, 271, 61))
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 490, 241, 231))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../../Downloads/XDZT.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        dotgui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(dotgui)
        self.statusbar.setObjectName("statusbar")
        dotgui.setStatusBar(self.statusbar)

        self.retranslateUi(dotgui)
        QtCore.QMetaObject.connectSlotsByName(dotgui)

    def retranslateUi(self, dotgui):
        _translate = QtCore.QCoreApplication.translate
        dotgui.setWindowTitle(_translate("dotgui", "MainWindow"))
        self.pushButton.setText(_translate("dotgui", "Run"))
        self.pushButton_2.setText(_translate("dotgui", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dotgui = QtWidgets.QMainWindow()
    ui = Ui_dotgui()
    ui.setupUi(dotgui)
    dotgui.show()
    sys.exit(app.exec_())
